const stampList = [
  { day: 1, status: "success", point: 7 },
  { day: 2, status: "partial", point: 3 },
  { day: 3, status: "partial", point: 4 },
  { day: 4, status: "partial", point: 4 },
  { day: 5, status: "success", point: 8 },
  { day: 6, status: "partial", point: 4 },
  { day: 7, status: "success", point: 7 },
  { day: 8, status: "success", point: 8 },
  { day: 9, status: "partial", point: 4 },
  { day: 10, status: "success", point: 7 },
  { day: 11, status: "success", point: 8 },
  { day: 12, status: "partial", point: 5 },
  { day: 13, status: "partial", point: 5 },
  { day: 14, status: "partial", point: 4 },
  { day: 15, status: "success", point: 8 },
  { day: 16, status: "partial", point: 2 },
  { day: 17, status: "partial", point: 5 },
  { day: 18, status: "partial", point: 3 },
  { day: 19, status: "partial", point: 5 },
  { day: 20, status: "success", point: 8 },
  { day: 21, status: "success", point: 7 },
  { day: 22, status: "success", point: 8 },
  { day: 23, status: "partial", point: 4 },
  { day: 24, status: "success", point: 7 },
  { day: 25, status: "success", point: 8 },
  { day: 26, status: "partial", point: 4 },
  { day: 27, status: "success", point: 7 },
  { day: 28, status: "partial", point: 4 },
  { day: 29, status: "none"},
  { day: 30, status: "none"},
];

export default stampList;