const stampList = [
  { day: 1, status: "success" },
  { day: 2, status: "partial" },
  { day: 3, status: "partial" },
  { day: 4, status: "partial" },
  { day: 5, status: "success" },
  { day: 6, status: "partial" },
  { day: 7, status: "success" },
  { day: 8, status: "success" },
  { day: 9, status: "partial" },
  { day: 10, status: "success" },
  { day: 11, status: "success" },
  { day: 12, status: "none" },
  { day: 13, status: "partial" },
  { day: 14, status: "none" },
  { day: 15, status: "success" },
  { day: 16, status: "none" },
  { day: 17, status: "none" },
  { day: 18, status: "partial" },
  { day: 19, status: "none" },
  { day: 20, status: "success" },
  { day: 21, status: "success" },
  { day: 22, status: "success" },
  { day: 23, status: "partial" },
  { day: 24, status: "success" },
  { day: 25, status: "success" },
  { day: 26, status: "partial" },
  { day: 27, status: "success" },
  { day: 28, status: "partial" },
  { day: 29 },
  { day: 30 },
];

export default stampList;